apiVersion: v2
name: hangarauth
description: HangarAuth Kubernetes Deployment
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.0.1
    condition: postgresql.enabled
