version: "2"

volumes:
  spongeauth-db:

services:
  db:
    image: postgres:9.6
    volumes:
      - spongeauth-db:/var/lib/postgresql
    environment:
      POSTGRES_USER: "hangarauth"
      POSTGRES_PASSWORD: "hangarauth"
      POSTGRES_DB: "hangarauth"
    ports:
      - "5433:5432"
  mail:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
  redis:
    image: redis:6.0.6
  app:
    build: .
    ports:
      - "8000:8000"
    links:
      - "db"
      - "mail"
      - "redis"
    environment:
      SECRET_KEY: "TzNc3RTpfVn1xxNV90PPGEfs7SZhy5"
      EMAIL_HOST: "mail"
      EMAIL_PORT: "1025"
      EMAIL_SSL: "false"
      EMAIL_TLS: "false"
      EMAIL_HOST_USER: "dum"
      EMAIL_HOST_PASSWORD: "dum"
      DB_NAME: "hangarauth"
      DB_USER: "hangarauth"
      DB_PASSWORD: "hangarauth"
      DB_HOST: "db"
      SSO_ENDPOINT_hangar: "{ 'sync_sso_endpoint': ('http://host.docker.internal:8080/api/sync_sso'), 'sso_secret': 'changeme', 'api_key': 'changeme' }"
      DEBUG: "true"