version: v0.10.0

dsn: "postgres://hangar:hangar@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4"

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3001
        - http://localhost:4433
  admin:
    base_url: http://kratos:4434/

session:
  lifespan: 720h # 30 days

selfservice:
  default_browser_return_url: http://localhost:3001/
  allowed_return_urls:
    - http://localhost:3001/

  methods:
    password:
      enabled: true
    oidc:
      enabled: true
    link:
      enabled: true
      config:
        lifespan: 1h
    totp:
      enabled: true
      config:
        issuer: HangarAuth
    lookup_secret:
      enabled: true
    webauthn:
      enabled: true
      config:
        passwordless: true
        rp:
          id: localhost
          origin: http://localhost:3001
          display_name: HangarAuth

  flows:
    error:
      ui_url: http://localhost:3001/error

    settings:
      ui_url: http://localhost:3001/account/settings
      privileged_session_max_age: 15m
      after:
        profile:
          hooks:
            - hook: web_hook
              config:
                method: POST
                url: "${BACKEND_HOST}/sync"
                body: file:///etc/config/kratos/hooks/settings/after/profile.jsonnet
                auth:
                  type: api_key
                  config:
                    in: header
                    name: X-Kratos-Hook-Api-Key
                    value: hookapikey-changeme

    recovery:
      enabled: true
      ui_url: http://localhost:3001/account/reset

    verification:
      enabled: true
      ui_url: http://localhost:3001/account/verify
      after:
        default_browser_return_url: http://localhost:3001/

    logout:
      after:
        default_browser_return_url: http://localhost:3001/?loggedOut

    login:
      ui_url: http://localhost:3001/account/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://localhost:3001/account/signup
      after:
        password:
          hooks:
            -
              hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - this-is-super-secret

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_id: identity_v1
  schemas:
    - id: identity_v1
      url: file:///etc/config/kratos/schemas/identity.v1.schema.json

courier:
  template_override_path: /etc/config/kratos/templates
  smtp:
    connection_uri: smtps://dum:dum@mailslurper:1025/?skip_ssl_verify=true&legacy_ssl=true
    from_address: noreply@mail.papermc.dev
