apiVersion: v1
kind: ConfigMap
metadata:
  name: hangarauth-hydra-config
  labels:
    {{- include "hangarauth.labels" . | nindent 4 }}
data:
  hydra.yaml: |
    serve:
      admin:
        cors:
          debug: true
        tls:
          allow_termination_from:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
      cookies:
        same_site_mode: Lax
      public:
        tls:
          allow_termination_from:
            - 10.0.0.0/16
            - 172.16.0.0/12
            - 192.168.0.0/16
    urls:
      self:
        public: https://auth.hangar.test/hydra/
        issuer: https://auth.hangar.test
      consent: https://auth.hangar.test/oauth/consent
      login: https://auth.hangar.test/oauth/login
      logout: https://auth.hangar.test/oauth/logout
      error: https://auth.hangar.test/error
    dsn: "postgres://hangarauth:hangarauth@hangarauth-postgresql:5432/hangarauth?sslmode=disable&max_conns=20&max_idle_conns=4"
    secrets:
      system:
        - "supersecuresupersecure"
    oidc:
      subject_identifiers:
        supported_types:
          - pairwise
          - public
        pairwise:
          salt: "supersecuresupersecure"
