apiVersion: v1
kind: ConfigMap
metadata:
  name: hangarauth-backend
  labels:
    {{- include "hangarauth.labels" . | nindent 4 }}
data:
  application.yaml: |
    spring:
      application:
        name: hangarauth-backend
      datasource:
        url: "jdbc:postgresql://{{ .Values.backend.config.postgresql.hostname }}:{{ .Values.backend.config.postgresql.port }}/{{ .Values.backend.config.postgresql.database }}{{ .Values.backend.config.postgresql.options }}"
        username: "{{ .Values.backend.config.postgresql.username }}"
        password: "{{ .Values.backend.config.postgresql.password }}"
    server:
      port: 8080
    management:
      server:
        port: 8081
      security:
        enabled: false
      endpoints:
        enabled-by-default: true
      endpoint:
        health:
          enabled: true
          probes:
            enabled: true
      health:
        livenessState:
          enabled: true
        readinessState:
          enabled: true
    auth:
      data-dir: /auth/data
      api-key: "${SSO_API_KEY}"
      public-host: "https://hangar-auth.benndorf.dev"
      kratos:
        public-url: "https://hangar-auth.benndorf.dev/kratos"
        admin-url: "http://kratos:4434"
      hydra:
        admin-url: "http://hydra:4445"
