apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hangarauth.fullname" . }}-kratos-courier
  labels:
    {{- include "hangarauth.labels" . | nindent 4 }}
spec:
  replicas: 1
  # we never want more than one
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "hangarauth.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "kratos-courier"
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret-kratos.yaml") . | sha256sum }}
      {{- with .Values.kratosCourier.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hangarauth.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "kratos-courier"
    spec:
      {{- with .Values.kratosCourier.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "hangarauth.fullname" . }}-kratos-config-volume
          secret:
            secretName: {{ include "hangarauth.fullname" . }}-kratos-config
        - name: {{ include "hangarauth.fullname" . }}-kratos-hooks-volume
          configMap:
            name: {{ include "hangarauth.fullname" . }}-kratos-hooks
        - name: {{ include "hangarauth.fullname" . }}-kratos-schemas-volume
          configMap:
            name: {{ include "hangarauth.fullname" . }}-kratos-schemas
        - name: {{ include "hangarauth.fullname" . }}-kratos-email-recovery-invalid-volume
          configMap:
            name: {{ include "hangarauth.fullname" . }}-kratos-email-recovery-invalid
        - name: {{ include "hangarauth.fullname" . }}-kratos-email-recovery-valid-volume
          configMap:
            name: {{ include "hangarauth.fullname" . }}-kratos-email-recovery-valid
        - name: {{ include "hangarauth.fullname" . }}-kratos-email-verification-invalid-volume
          configMap:
            name: {{ include "hangarauth.fullname" . }}-kratos-email-verification-invalid
        - name: {{ include "hangarauth.fullname" . }}-kratos-email-verification-valid-volume
          configMap:
            name: {{ include "hangarauth.fullname" . }}-kratos-email-verification-valid
      serviceAccountName: {{ include "hangarauth.kratosCourier.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.kratosCourier.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "hangarauth.fullname" . }}-kratos-courier
          securityContext:
            {{- toYaml .Values.kratosCourier.securityContext | nindent 12 }}
          image: "{{ .Values.kratosCourier.image.repository }}:{{ .Values.kratosCourier.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.kratosCourier.image.pullPolicy }}
          command: ["kratos"]
          args: ["courier", "watch", "--config", "/etc/config/kratos.yaml"]
          volumeMounts:
            - name: {{ include "hangarauth.fullname" . }}-kratos-config-volume
              mountPath: /etc/config
              readOnly: true
            - name: {{ include "hangarauth.fullname" . }}-kratos-hooks-volume
              mountPath: /etc/hangarauth/hooks
              readOnly: true
            - name: {{ include "hangarauth.fullname" . }}-kratos-schemas-volume
              mountPath: /etc/hangarauth/schemas
              readOnly: true
            - name: {{ include "hangarauth.fullname" . }}-kratos-email-recovery-invalid-volume
              mountPath: /etc/hangarauth/email/recovery/invalid
              readOnly: true
            - name: {{ include "hangarauth.fullname" . }}-kratos-email-recovery-valid-volume
              mountPath: /etc/hangarauth/email/recovery/valid
              readOnly: true
            - name: {{ include "hangarauth.fullname" . }}-kratos-email-verification-invalid-volume
              mountPath: /etc/hangarauth/email/verification/invalid
              readOnly: true
            - name: {{ include "hangarauth.fullname" . }}-kratos-email-verification-valid-volume
              mountPath: /etc/hangarauth/email/verification/valid
              readOnly: true
          resources:
            {{- toYaml .Values.kratosCourier.resources | nindent 12 }}
      {{- with .Values.kratosCourier.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kratosCourier.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kratosCourier.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kratosCourier.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
