apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hangarauth.fullname" . }}-backend
  labels:
    {{- include "hangarauth.labels" . | nindent 4 }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hangarauth.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "backend"
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret-hangarauth-backend.yaml") . | sha256sum }}
      {{- with .Values.backend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hangarauth.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "backend"
    spec:
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hangarauth.backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ include "hangarauth.fullname" . }}-backend-config-volume
          secret:
            secretName: {{ include "hangarauth.fullname" . }}-backend
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: management
              containerPort: 8081
              protocol: TCP
          env:
            - name: spring.config.location
              value: "classpath:/application.yml,/auth-backend/config/application.yaml"
          volumeMounts:
            - name: {{ include "hangarauth.fullname" . }}-backend-config-volume
              mountPath: /auth-backend/config
              readOnly: true
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: management
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: management
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
