apiVersion: v1
kind: Secret
metadata:
  name: hangarauth-hydra-config
  labels:
    {{- include "hangarauth.labels" . | nindent 4 }}
type: Opaque
stringData:
  hydra.yaml: |
    serve:
      admin:
        cors:
          debug: true
        tls:
          allow_termination_from:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
      cookies:
        same_site_mode: Lax
      public:
        tls:
          allow_termination_from:
            - 10.0.0.0/16
            - 172.16.0.0/12
            - 192.168.0.0/16
    urls:
      self:
        public: {{ .Values.base.authHost }}/hydra/
        issuer: {{ .Values.base.authHost }}
      consent: {{ .Values.base.authHost }}/oauth/consent
      login: {{ .Values.base.authHost }}/oauth/login
      logout: {{ .Values.base.authHost }}/oauth/logout
      error: {{ .Values.base.authHost }}/error
    dsn: "postgres://{{ .Values.hydra.config.postgresql.username }}:{{ .Values.hydra.config.postgresql.password }}@{{ .Values.hydra.config.postgresql.hostname }}:{{ .Values.hydra.config.postgresql.port }}/{{ .Values.hydra.config.postgresql.database }}{{ .Values.hydra.config.postgresql.options }}"
    secrets:
      system:
        - "{{ .Values.hydra.config.systemSecret }}"
    oidc:
      subject_identifiers:
        supported_types:
          - pairwise
          - public
        pairwise:
          salt: "{{ .Values.hydra.config.oidcSalt }}"
