apiVersion: v1
kind: Secret
metadata:
  name: hangarauth-frontend
  labels:
    {{- include "hangarauth.labels" . | nindent 4 }}
type: Opaque
stringData:
  NITRO_PUBLIC_KRATOS_PUBLIC: "{{ .Values.base.authHost }}/kratos"
  NITRO_KRATOS: "{{ .Values.frontend.config.kratos.backendUrl }}"
  NITRO_PUBLIC_PUBLIC_HOST: "{{ .Values.base.authHost }}"
  NITRO_PUBLIC_BACKEND_HOST: "{{ .Values.frontend.config.backendHost }}"
  NITRO_PUBLIC_HANGAR_HOST: "{{ .Values.base.hangarHost }}"
  DEBUG: "{{ .Values.frontend.config.debug }}"
  NITRO_PUBLIC_SIGNUP_DISABLED: "{{ .Values.frontend.config.signupDisabled }}"
