apiVersion: v1
kind: Secret
metadata:
  name: hangarauth-backend
  labels:
    {{- include "hangarauth.labels" . | nindent 4 }}
type: Opaque
stringData:
  application.yaml: |
    spring:
      application:
        name: hangarauth-backend
      datasource:
        url: "jdbc:postgresql://{{ .Values.backend.config.postgresql.hostname }}:{{ .Values.backend.config.postgresql.port }}/{{ .Values.backend.config.postgresql.database }}{{ .Values.backend.config.postgresql.options }}"
        username: "{{ .Values.backend.config.postgresql.username }}"
        password: "{{ .Values.backend.config.postgresql.password }}"
    server:
      port: 8080
    management:
      server:
        port: 8081
      security:
        enabled: false
      endpoints:
        enabled-by-default: true
      endpoint:
        health:
          enabled: true
          probes:
            enabled: true
      health:
        livenessState:
          enabled: true
        readinessState:
          enabled: true
    auth:
      data-dir: /auth/data
      api-key: "{{ .Values.base.sso.apiKey }}"
      public-host: "{{ .Values.base.authHost }}"
      hangar-frontend-host: "{{ .Values.base.hangarHost }}"
      hangar-backend-host: "http://hangar-backend:8080"
      allowed-origins: "{{ .Values.backend.config.auth.allowedOrigins }}"
      kratos:
        public-url: "{{ .Values.base.authHost }}/kratos"
        public-backend-url: "{{ .Values.backend.config.auth.kratos.publicBackendUrl }}"
        admin-url: "{{ .Values.backend.config.auth.kratos.adminUrl }}"
      hydra:
        admin-url: "{{ .Values.backend.config.auth.hydra.adminUrl }}"
      storage:
        type: "{{ .Values.backend.config.storage.type }}"
        access-key: "{{ .Values.backend.config.storage.accessKey }}"
        secret-key: "{{ .Values.backend.config.storage.secretKey }}"
        bucket: "{{ .Values.backend.config.storage.bucket }}"
        object-storage-endpoint: "{{ .Values.backend.config.storage.objectStorageEndpoint }}"
        cdn-endpoint: "{{ .Values.backend.config.storage.cdnEndpoint }}"
        cdnIncludeBucket: "{{ .Values.backend.config.storage.cdnIncludeBucket }}"
      invite:
        enabled: {{ .Values.backend.config.invite.enabled }}
        api-key: "{{ .Values.backend.config.invite.apiKey }}"
