apiVersion: v1
kind: Service
metadata:
  name: {{ include "hangarauth.fullname" . }}-kratos
  labels:
    {{- include "hangarauth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kratos.service.type }}
  ports:
    - port: {{ .Values.kratos.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hangarauth.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "kratos"
