apiVersion: v1
kind: Service
metadata:
  name: {{ include "hangarauth.fullname" . }}-hydra
  labels:
    {{- include "hangarauth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hydra.service.type }}
  ports:
    - port: {{ .Values.hydra.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 4445
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "hangarauth.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "hydra"
