apiVersion: v1
kind: Service
metadata:
  name: {{ include "hangarauth.fullname" . }}-backend
  labels:
    {{- include "hangarauth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hangarauth.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "backend"
  topologyKeys:
    - "kubernetes.io/hostname"
    - "topology.kubernetes.io/zone"
    - "topology.kubernetes.io/region"
    - "*"