apiVersion: v1
kind: Service
metadata:
  name: {{ include "hangarauth.fullname" . }}-kratos-courier
  labels:
    {{- include "hangarauth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kratosCourier.service.type }}
  ports:
    - port: {{ .Values.kratosCourier.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 4434
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "hangarauth.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "kratos-courier"
