{{- if .Values.kratos.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hangarauth.kratos.serviceAccountName" . }}
  labels:
    {{- include "hangarauth.labels" . | nindent 4 }}
  {{- with .Values.kratos.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
