apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: hangarauth
  labels:
    hangarauth-service: backend
spec:
  ports:
    - port: 8080
      name: backend
  selector:
    hangarauth-service: backend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
  namespace: hangarauth
  labels:
    hangarauth-service: backend
spec:
  serviceName: "backend"
  replicas: 1
  selector:
    matchLabels:
      hangarauth-service: backend
  template:
    metadata:
      labels:
        hangarauth-service: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/papermc/hangarauth_backend
          env:
            {{- range $key, $value := .Values.env.backend }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          stdin: true
          volumeMounts:
            - mountPath: /auth/data
              name: hangarauth-data
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
      restartPolicy: Always
      volumes:
        - name: hangarauth-data
          persistentVolumeClaim:
            claimName: hangarauth-data
  volumeClaimTemplates:
    - metadata:
        name: hangarauth-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
