apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: hangarauth
  labels:
    hangarauth-service: frontend
spec:
  ports:
    - port: 3000
      name: frontend
  selector:
    hangarauth-service: frontend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frontend
  namespace: hangarauth
  labels:
    hangarauth-service: frontend
spec:
  serviceName: "frontend"
  replicas: 1
  selector:
    matchLabels:
      hangarauth-service: frontend
  template:
    metadata:
      labels:
        hangarauth-service: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/papermc/hangarauth_frontend
          env:
            {{- range $key, $value := .Values.env.frontend }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          stdin: true
          # todo better probes
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 60
      restartPolicy: Always
