apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    hangarauth-service: ingress
  name: hangarauth
  namespace: hangarauth
spec:
  rules:
    - host: {{ .Values.ingressHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
          - path: /kratos
            pathType: Prefix
            backend:
              service:
                name: kratos
                port:
                  number: 4433
          - path: /hydra
            pathType: Prefix
            backend:
              service:
                name: hydra
                port:
                  number: 4444
