version: '3.7'

services:
  kratos-migrate:
    build:
      context: kratos
      args:
        API_HOST: "http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:8081"
        BACKEND_HOST: "http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:8080"
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
  kratos:
    depends_on:
      - kratos-migrate
    restart: unless-stopped
    build:
      context: kratos
      args:
        API_HOST: "http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:8081"
        BACKEND_HOST: "http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:8080"
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
  hydra-migrate:
    build:
      context: hydra
    command: -c /etc/config/hydra/hydra.yml migrate sql -e --yes
    restart: on-failure
  hydra:
    depends_on:
      - hydra-migrate
    build:
      context: hydra
    restart: unless-stopped
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    environment:
      - "OAUTH2_EXPOSE_INTERNAL_ERRORS=true"
      - "LOG_LEVEL=debug"
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
      - '1025:1025'
  cockroach:
    image: cockroachdb/cockroach:latest-v21.2
    ports:
      - "26257:26257"
      - "26000:8080"
    volumes:
      - cockroach_data:/cockroach/cockroach-data
    command:
      - "start-single-node"
      - "--insecure"

volumes:
  cockroach_data:

networks:
  default:
    name: hangar-network
