version: '3.7'

services:
  kratos-migrate:
    build:
      context: kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
  kratos:
    depends_on:
      - kratos-migrate
    restart: unless-stopped
    build:
      context: kratos
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    extra_hosts:
      - "host.docker.internal:host-gateway" # for hooks
  hydra-migrate:
    build:
      context: hydra
    command: -c /etc/config/hydra/hydra.yml migrate sql -e --yes
    restart: on-failure
  hydra:
    depends_on:
      - hydra-migrate
    build:
      context: hydra
    restart: unless-stopped
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    environment:
      - "OAUTH2_EXPOSE_INTERNAL_ERRORS=true"
      - "LOG_LEVEL=debug"
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
      - '1025:1025'
  postgres:
    build: ./postgres
    environment:
      POSTGRES_MULTIPLE_DATABASES: hydra,kratos
      POSTGRES_DB: hangar
      POSTGRES_USER: hangar
      POSTGRES_PASSWORD: 'hangar'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  default:
    name: hangar-network
