serve:
  admin:
    cors:
      debug: true
  cookies:
    same_site_mode: Lax
  public:
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3000

log:
  leak_sensitive_values: true

urls:
  self:
    issuer: http://localhost:4444
  consent: http://localhost:3001/oauth/consent
  login: http://localhost:3001/oauth/login
  logout: http://localhost:3001/oauth/logout
  error: http://localhost:3001/error

dsn: "postgres://hangar:hangar@postgres:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4"

secrets:
  system:
    - this-is-super-secret

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis
