version: v0.10.0

dsn: "see env"

serve:
  public:
    base_url: https://hangar-auth.benndorf.dev/kratos
    cors:
      enabled: true
      allowed_origins:
        - https://hangar-auth.benndorf.dev
        - http://localhost:4433
  admin:
    base_url: http://hangarauth_kratos:4434/

cookies:
  domain: benndorf.dev

session:
  lifespan: 720h # 30 days

selfservice:
  default_browser_return_url: https://hangar-auth.benndorf.dev/
  allowed_return_urls:
    - https://hangar-auth.benndorf.dev/

  methods:
    password:
      enabled: true
    oidc:
      enabled: true
    link:
      enabled: true
      config:
        lifespan: 1h
    totp:
      enabled: true
      config:
        issuer: HangarAuth
    lookup_secret:
      enabled: true
    webauthn:
      enabled: true
      config:
        passwordless: true
        rp:
          id: benndorf.dev
          origin: https://hangar-auth.benndorf.dev
          display_name: HangarAuth

  flows:
    error:
      ui_url: https://hangar-auth.benndorf.dev/error

    settings:
      ui_url: https://hangar-auth.benndorf.dev/account/settings
      privileged_session_max_age: 15m
      after:
        profile:
          hooks:
            - hook: web_hook
              config:
                method: POST
                url: "http://hangar_backend:8080/sync"
                body: file:///etc/config/kratos/hooks/settings/after/profile.jsonnet
                auth:
                  type: api_key
                  config:
                    in: header
                    name: X-Kratos-Hook-Api-Key
                    value: hookapikey-changeme

    recovery:
      enabled: true
      ui_url: https://hangar-auth.benndorf.dev/account/reset

    verification:
      enabled: true
      ui_url: https://hangar-auth.benndorf.dev/account/verify
      after:
        default_browser_return_url: https://hangar-auth.benndorf.dev/

    logout:
      after:
        default_browser_return_url: https://hangar-auth.benndorf.dev/?loggedOut

    login:
      ui_url: https://hangar-auth.benndorf.dev/account/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: https://hangar-auth.benndorf.dev/account/signup
      after:
        default_browser_return_url: "https://hangar-auth.benndorf.dev/account/settings?new=true"
        password:
          hooks:
            -
              hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - "see env"

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_id: identity_v1
  schemas:
    - id: identity_v1
      url: file:///etc/config/kratos/schemas/identity.v1.schema.json

courier:
  template_override_path: /etc/config/kratos/templates
  smtp:
    # overriden in env
    connection_uri: smtps://dum:dum@hangarauth_mail:1025/?skip_ssl_verify=true&legacy_ssl=true
    from_address: noreply@papermc.dev
