server:
  port: 8081

auth:
  public-host: "http://localhost:3001"
  api-key: "supersecret"
  hangar-frontend-host: "http://localhost:3333"
  hangar-backend-host: "http://localhost:3333"
  allowed-origins:
    - "http://localhost:3000"
    - "http://localhost:3333"
  kratos:
    public-url: "http://localhost:4433"
    public-backend-url: "http://localhost:4433"
    admin-url: "http://localhost:4434"
  hydra:
    admin-url: "http://localhost:4445"
  image:
    quality: 0.35
    size: 256
  storage:
    type: "local"
    work-dir: backend/work
    access-key: "maaWFU0y2agLgJBD"
    secret-key: "toOBAwlz3ZC6c4dvbFh7Ywk8Y2J4b3kS"
    bucket: "test"
    object-storage-endpoint: "http://127.0.0.1:9000"
    cdn-endpoint: "http://127.0.0.1:9000"
    cdn-include-bucket: true
  invite:
    enabled: false
    api-key: "hookapikey-changeme"

spring:
  application:
    name: hangarauth-backend
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/kratos?currentSchema=auth
    username: hangar
    password: hangar
  flyway:
    default-schema: auth
    create-schemas: true
    schemas: auth

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
  devtools:
    restart:
      additional-exclude: work/**
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat

  cloud:
    aws:
      s3:
        endpoint: "${auth.storage.object-storage-endpoint}"
    kubernetes:
      secrets:
        enableApi: true

logging:
  level:
    io.papermc.hangarauth: DEBUG
    org.springframework: INFO
