name: Build Frontend

on:
  # allow manual dispatch
  workflow_dispatch:
  # run on PRs
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_build.yml'

concurrency:
  group: ${{ github.ref }}-frontend-build
  cancel-in-progress: true

jobs:
  builds:
    runs-on: ubuntu-latest

    env:
      CI: true

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: "/home/runner/.local/share/pnpm/store/v3"
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install frontend deps
        run: pnpm install --frozen-lockfile

      - name: Lint frontend
        run: pnpm prep && pnpm lint:eslint

      - name: Build frontend
        run: pnpm build
